services:
  traefik:
    ports:
    - "80:80"
    - "443:443"
    networks:
      development:
    volumes:
      # Mount the Docker socket as read-only so Traefik can listen to events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./.infrastructure/conf/traefik/dev/traefik.yml:/traefik.yml:ro
      - ./.infrastructure/conf/traefik/dev/traefik-certs.yml:/traefik-certs.yml
      - ./.infrastructure/conf/traefik/dev/certificates/:/certificates

  php:
    build:
      target: development
      args:
        USER_ID: ${SPIN_USER_ID}
        GROUP_ID: ${SPIN_GROUP_ID}
    volumes:
      - .:/var/www/html/
    networks:
      - development
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel.rule=HostRegexp(`localhost`)"
      - "traefik.http.routers.laravel.entrypoints=web"
      - "traefik.http.services.laravel.loadbalancer.server.port=8080"
      - "traefik.http.services.laravel.loadbalancer.server.scheme=http"
  mongodb:
    image: mongo:latest
    hostname: mongo
    restart: unless-stopped
    command: --replSet rs0
    ports:
      - "27017:27017"
    environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: laravel
    volumes:
      - ./.infrastructure:/mongodb
    networks:
      - development
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' localhost:27017/test --quiet
      interval: 2s
      timeout: 3s
      retries: 5
  mongo-init:
    image: mongo:latest
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - development
    command: >
      sh -c "sleep 5; mongosh --host mongo:27017 --eval '
      rs.initiate( {
        _id : \"rs0\",
        members: [
          { _id: 0, host: \"mongo:27017\" }
        ]
      })
      '"
  node:
    image: node:20
    volumes:
      - .:/usr/src/app/
    working_dir: /usr/src/app/
    networks: 
      - development

  mailpit:
      image: axllent/mailpit
      networks:
        - development
      ports:
        - "8025:8025"

networks:
  development: